### ISSUE TITLE
Commit 3325024f1 uses C++23 features

### ISSUE THREAD

**Issue by akreuzkamp** [mbeutel/makeshift#7]
include/makeshift/metadata.hpp:156 is `static constexpr auto values_ = metadata::values<T, ReflectorT>();`
which uses static variables in constexpr functions. This is only allowed since [P2242R3](https://wg21.link/P2242R3), which is part of C++23, only.

GCC 12 fails with
`.../include/makeshift/metadata.hpp:156:27: error: 'values_' defined 'static' in 'constexpr' function only available with '-std=c++2b' or '-std=gnu++2b'`

**Comment by mbeutel** [comment]
Thanks. This also showed up in [CI](https://github.com/mbeutel/makeshift/runs/8842473792), and I even noticed it locally with Clang and [fixed it](https://github.com/mbeutel/makeshift/commit/72df1b859dd79e9ae8a7f5ab61c9974f1c15eb22), but of course I forgot to push my changes.
